Added support for Laravel 5.8
Crinsane/LaravelShoppingcart pull request #595
Opened 2019-11-29 02:42 UTC by jabarrioss

I fixed a bug when firing events, from laravel 5.5 to fire an evento you should use the Event::dipatch() method instead of the Event::Fire() method

2019-11-29 17:37 UTC, bumbummen99 requested changes
Hey, please do not change the package name when you plan to create a PR. The proper way to handle this case would be to create an additional branch just for backporting/pr and keep the original package name there. Also do the tests still run properly?

2019-11-29 17:37 UTC, bumbummen99 commented on composer.json
> +    "name": "jabarrioss/shoppingcart",
Please remove this change (from the PR).

2019-11-29 17:37 UTC, bumbummen99 commented on src/Cart.php
> +
Nit: Is this change required?

2019-11-29 17:40 UTC, jabarrioss commented
> Hey, please do not change the package name when you plan to create a PR. The proper way to handle this case would be to create an additional branch just for backporting/pr and keep the original package name there. Also do the tests still run properly?

I haven't run the test I changed the name of the package because I have to use for a project that I'm working on

2019-11-29 20:25 UTC, bumbummen99 commented
@jabarrioss That is absolutely fine, no worries! :) But this PR simply can not be merged with a different package name and you can not simply change it as your project depends on it. That is why i suggested creating the pr with a different branch that still has the original package-name but all the other changes.

2020-03-02 02:23 UTC, rbergDrox commented
@jabarrioss  @bumbummen99  here my PR #608  
php version for laravel  >=7.1.3
Logout event  signature has changed I fixed by adding web guard
I passed the tests

2021-10-27 20:39 UTC, closed without merging